### ISSUE TITLE
First step starts after sequence run

### ISSUE THREAD

**Issue by Dystopian** [imurvai/brickcontroller2#102]
BrickController 2 3.3 from Google Play, Android 11.

Repro:
- create sequence with 2 steps: `100% 1000ms`, `0% 1000ms`, `Loop` and `Interpolate` disabled;
- add button for sequence start, use `NormalMotor` channel type;
- press button to start sequence;
- observe motor rotating for 1000ms, then stopping for 1000ms; then motor starts rotating infinitely instead of stop.

From several tests I found that motor starts rotating exactly with value from the 1st step.

As workaround one can add `0% 300ms` (minimal value) as 1st step. Then motor just stops at the end of sequence.

**Comment by vicocz** [comment]
Hi,
AFAIK sequences are internally executed using a timer with 50 ms interval. In case total duration of non-looped sequence is multiple of 50 milliseconds, there seems to be a value from the first step applied and set to a given channel.

There seems to be pretty simnple workaround: in your case choose duration of the last step `1001ms` instead of `1000`.

**Comment by Dystopian** [comment]
> duration of the last step `1001ms` instead of `1000`

Thank you, it works :) And thanks for PR.
